
- name: Install the release.asc ke
  shell: rpm --import 'https://ceph.com/git/?p=ceph.git;a=blob_plain;f=keys/release.asc'

- name: Install the autobuild.asc key
  shell: rpm --import 'https://ceph.com/git/?p=ceph.git;a=blob_plain;f=keys/autobuild.asc'

- name: Install ceph extra repo
  copy: src={{item}}
        dest=/etc/yum.repos.d/{{item}}
  with_items:
    - ceph.repo
  tags:
    - repos

- name: Install ceph extra repo
  file: path=/etc/yum.repos.d/{{item}}
        state=absent
  with_items:
    - ceph-apache.repo
    - ceph-extras.repo
    - ceph-fastcgi.repo
  tags:
    - repos

- name: Install additional repo
  shell: rpm -Uvh http://ceph.com/rpm-emperor/el6/noarch/ceph-release-1-0.el6.noarch.rpm
  ignore_errors: yes

