---
- hosts: all
  vars_files:
    - group_vars/networks.yml
    - group_vars/{{ ansible_os_family }}.yml
    - vars/{{inventory_hostname}}.yml
  roles:
    - { role: network, is_sys: true }
    - { role: multicast }
    - { role: firewall, is_sys: true, is_sysop: false, is_core: false }
