
- name: Enable loghost client
  template: src=client.{{ansible_os_family}}.j2
            dest=/etc/syslog-ng/conf.d/20-client.conf
            owner=root
            group=root
            mode=0644
  notify:
    - Restart syslog-ng
  tags:
    - config
