- name: Enable syslog-ng loghost
  template: src=loghost.j2
            dest=/etc/syslog-ng/conf.d/10-loghost.conf
            owner=root
            group=root
            mode=0644
  notify:
    - Restart syslog-ng
  tags:
    - config

- name: Enable log compressor
  template: src=compress-syslog.j2
            dest=/etc/cron.daily/compress-syslog
            owner=root
            group=root
            mode=0755
  tags:
    - config
    - compress
