- name: Install umask repo
  template: src=umask.repo.j2
            dest=/etc/yum.repos.d/umask.repo
            owner=root
            group=root
  when: ansible_os_family == "RedHat"
  tags:
    - repo
    - packages

- name: Stop rsyslog
  service: name=rsyslog
           state=stopped
           enabled=no
  tags:
    - prepare
  ignore_errors: yes

- name: Uninstall rsyslog for sure
  yum: name=rsyslog
       state=absent
  when: ansible_os_family == "RedHat"
  tags:
    - prepare

- name: Install syslog-ng packages
  yum: name={{item}}
       state=latest
       enablerepo=umask
  with_items:
    - syslog-ng
    - syslog-ng-libdbi
  when: ansible_os_family == "RedHat"
  tags:
    - packages

- name: Create /etc/syslog-ng/conf.d
  file: path=/etc/syslog-ng/conf.d
        owner=root
        group=root
        state=directory
  tags:
    - config
    - directories

- name: Install syslog-ng.conf
  template: src=syslog-ng.{{ansible_distribution}}.conf.j2
            dest=/etc/syslog-ng/syslog-ng.conf
            owner=root
            group=root
            backup=yes
  tags:
    - config

- name: Start syslog-ng
  service: name=syslog-ng
           state=started
           enabled=yes
